# -*- coding: utf-8 -*-
"""balanced.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxNhP39CKE3YeTwdzkhmpBNs8zTJeqIx
"""

def balanced(exp):
    stack = []

    for ch in exp:
        if ch == '(':
            stack.append(ch)
        elif ch == ')':
            if not stack:
                return False
            stack.pop()

    return len(stack) == 0

exp = input("Enter expression: ")

if balanced(exp):
    print("Balanced")
else:
    print("Not Balanced")